name: flutter_tinder
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  bloc: ^3.0.0

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.0.0

  device_preview: ^0.3.0+1
  dio: ^3.0.9

  equatable: ^1.1.1

  flutter_localized_locales: ^1.0.3
  flutter_bloc: ^3.2.0
  fluttertoast: ^3.1.3
  flutter_tindercard: ^0.1.8
  flutter_screenutil: ^1.0.2
  flutter_shimmer: ^1.2.0

  get_it: ^4.0.0

  intl: ^0.16.0

  logger: ^0.8.3

  path_provider: ^1.6.5
  page_transition: ^1.1.5

  sqflite: ^1.2.2+1
  shared_preferences: ^0.5.6+2
  shimmer: ^1.1.0

  timeago: ^2.0.26


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^4.0.0
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true